version: 2
 jobs:
   one:
     docker:
       - image: debian:stretch
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 25
   two:
     docker:
       - image: debian:stretch
     steps:
       - checkout
       - run: echo "A more familiar hi"
       - run: sleep 15
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
